name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3
      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: "Install Dependencies"
        run: npm ci
      - name: "Run NPM Build"
        run: npm run build
